apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: teyalite/reddit-clone-api:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOSTNAME
              value: postgres-service.default
            - name: DB_USERNAME
              value: postgres
            - name: DB_DATABASE
              value: reddit-clone
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              value: password123
            - name: JWT_SECRET_KEY
              value: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - name: JWT_ALGORITHM
              value: HS256
            - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
              value: "300"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
